# language: yaml
# Cấu hình chung cho tất cả các môi trường
spring:
  profiles:
    active: dev # Profile mặc định khi chạy local
  jpa:
    hibernate:
      ddl-auto: update # Sẽ được ghi đè trong môi trường docker
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  file:
    name: logs/viecinema.log
  level:
    root: INFO
    com.viecinema: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

security:
  jwt:
    secret: ${JWT_SECRET:6yJp4vC1S3f7mQ9hF2uX8LgR0kWzB5Pd7aTnV4YqH0cJr9KxNw} # Ưu tiên biến môi trường, nếu không có thì dùng giá trị mặc định
    expiration: ${JWT_EXPIRATION:7d}

app:
  name: viecinema
  timezone: UTC
  development:
    # Khi true, API showtime sẽ bỏ qua bộ lọc ngày và thời gian, lấy tất cả suất chiếu
    ignore-showtime-time-filter: false
  base-url: http://localhost:8080  # Dev
  frontend-url: http://localhost:3000  # URL frontend để redirect

vnpay:
  # Thông tin từ VNPay Sandbox
  tmn-code: HLBPLRMV # VD:  DEMOV01P
  hash-secret: PM6GQJ9RQ8FYXHTC55O1NR1TW0MR361A  # VD:  LMREXAMPLEKEY123456789
  api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${app.base-url}/api/payments/vnpay/callback  # URL nhận kết quả
  ipn-url: ${app.base-url}/api/payments/vnpay/ipn  # URL nhận IPN (Instant Payment Notification)

  # Cấu hình timeout
  timeout: 15  # 15 phút

  # Cấu hình version
  version: 2.1.0
  command:  pay
  currency-code: VND
  locale: vn  # vn hoặc en

---
# Cấu hình cho môi trường Development (dev)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/movie_booking_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"

---
# Cấu hình cho môi trường Docker
spring:
  config:
    activate:
      on-profile: docker
  # Trong môi trường docker, các giá trị datasource sẽ được cung cấp hoàn toàn
  # bởi biến môi trường trong docker-compose.yml, không cần định nghĩa ở đây.
  jpa:
    hibernate:
      ddl-auto: validate # An toàn hơn cho môi trường "giống-production"
